### ISSUE TITLE
iOS build error 'SDWebImage/SDWebImage.h' file not found

### ISSUE THREAD

**Issue by levepic** [gbumps/react-native-screenguard#32]
iOS build fails with

'SDWebImage/SDWebImage.h' file not found

at

#import "ScreenGuard.h"
#import <SDWebImage/SDWebImage.h>

Did arch -x86_64 pod install also with update, desintegrate and then pod install again, clean build folder. Could it be something on my side?

    "react-native": "^0.70.8",
    "react-native-screenguard": "^0.3.0",

platform :ios, '12.4'

**Comment by gbumps** [comment]
it is for `beta` version only, please revise (README.md)[https://github.com/gbumps/react-native-screenguard#readme] carefully before proceeding.

**Comment by levepic** [comment]
I have installed stable, not beta. Do you mean I have to install Beta for ios or what to look for in Readme? Or I could somehow exclude SDWebImage using the basic stable version? How? I need only the basic functionality or android only is still OK if I can build on ios.

**Comment by gbumps** [comment]
I still don't understand what your intention of integration with `SDWebImage` on the `stable` version. Please describe more detailed.

**Comment by levepic** [comment]
OK I see now: I did not want to install beta or SDWebImage. I just did 

npm install react-native-screenguard --save

When trying to build on ios it raises the error. It seems like the stable version also tries to include SDWebImage.

**Comment by gbumps** [comment]
yes. Just remove the ` <SDWebImage/SDWebImage.h>` ad rebuild, I'm doing on a fix for the previous one

**Comment by levepic** [comment]
Thank you!It works!Will try it on live app after some testing!:)

**Comment by gbumps** [comment]
This issue has been resolved at version `0.3.2`, please install and rebuild. Thanks!

**Comment by ncoen97** [comment]
@gbumps I think the issue is back. I just installed via `yarn add react-native-screenguard` (and run pod install). After building, I get

```
(node_modules/react-native-screenguard/ios/ScreenGuard.mm:2:9)
> 2 | #import "SDWebImage/SDWebImage.h"
    |         ^ 'SDWebImage/SDWebImage.h' file not found
```

Am I missing some installation step?

**Comment by gbumps** [comment]
hi @ncoen97, please go back to the stable version 0.3.6 while i'm reviewing the code once more.

thanks!

**Comment by ncoen97** [comment]
Great, thanks for the reply!

Are there any known issues in 0.3.6 I should be aware of? I recall seeing some bugfix commits between the 0.3.6 and 0.4 history 🤔

**Comment by gbumps** [comment]
there are very small update between `0.4.0` and `0.3.6`, so don't worry about it.

I have been mismatched with the code between stable version and beta version. All 2 versions will be merged into one on the next release.

**Comment by wongzigii** [comment]
Same issue.

**Comment by gbumps** [comment]
Hi @ncoen97 @wongzigii, version 1.0.0 has been fully released, please install and rebuild.

Thanks!
